# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install --ignore-scripts --no-progress --no-audit

# Copy source files
COPY . .

# Expose no port (stdio transport)

# Default command
CMD ["node", "index.js"]
